Todo/config/routes.rb
Rails.application.routes.draw do

  root to: 'tasks#index'

  resources :tasks, only: [:index,:create]

end

Todo/app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true
  validates :memo, presence: true
  validates :position, presence: true
end

Todo/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @task = Task.new
    @tasks = Task.all
  end

  def create
    @tasks = Task.all
    @task = Task.create(task_params)
    redirect_to '/'
  end

  private
  def task_params
    params.require(:task).permit(:name, :memo, :position)
  end
end

Todo/app/helpers/tasks_helper.rb
module TasksHelper
end

Todo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Todo/app/views/tasks/index.html.erb
<%= form_with(model: @task, url: tasks_path , method: :post, local: true) do |form| %>
 <div>
 <%= form.text_field :name, placeholder: "名前" %>
 </div>
 <div>
 <%= form.text_area :memo, placeholder: "内容" %>
 </div>
 <div>
 <%= form.text_field :position, placeholder: "順番" %>
 </div>
 <div>
 <%= form.submit "POST"%>
 </div>
<% end %>

<% @tasks.each do |task| %>
  <div class="box">
    <div class="name"><%= task.name %></div>
    <div class="memo"><%= task.memo %></div>
  </div>
<% end %>